adding .gitattributes file
temporalio/sdk-dotnet pull request #92
Opened 2022-06-07 19:34 UTC by mightyshazam

### Summary

Added a .gitattributes file so that we will have normalized line endings across the repo

#### Motivation

Development is across platforms, and we don't want to spend time dealing with differences in line endings.

2022-06-09 16:31 UTC, macrogreg requested changes
Nice! Thanks for doing this!

A few details/comments. :)

2022-06-09 16:31 UTC, macrogreg commented on Src/.gitattributes
> +# Set the default behavior, in case people don't have core.autocrlf set.
Also (separate item), you did a pretty good job on listing all the file extensions, but a few got forgotten. :)
I run this PowerShell command in the repo root:
`Get-Childitem . -Force -Recurse | WHERE { -NOT $_.PSIsContainer } | Group Extension -NoElement | Sort Count -Desc`

Here are the results. I marked what you already covered, what we should consider adding, and what's likely better staying binary:

Count | Name | Type  | Done?
----- |----  | --- | -----
 1959| |folders and no-ext files. treat as binary | nothing to do
  187| .cs  | text, auto | done
   25| .md  | text, auto | done
   19| .yml  | text, auto| **please add**
   14 |.txt  | they are all in `.vs` folders, so in gitignore. but generally, _text, auto_| **please add**
   13| .sample  | also in `.vs`. never mind these | nothing to do
   8| .csproj  |  text, auto | done
  7 |.bat  | text, CRLF | done
  7 |.props  |  text, auto | done
  6 |.pem  | binary | nothing to do
  5 |.json  |  text, auto | **please add**
  5 |.suo  | only in `.vs`. consider them binary | nothing to do
  4 |.v2  | only in `.vs`. consider them binary | nothing to do
  4 |.v1  |only in `.vs`. consider them binary | nothing to do
  4 |.jpg  | binary | you marked them, but omitting them should be sufficient as bin is default
  3 |.sln  | text, CRLF | done
  3 |.idx  | only in `.git`. consider them binary | nothing to do
  3 |.pack  | only in `.git`. consider them binary | nothing to do
  2 |.marker  | text, auto | done
  2 |.manifest  | only in `.vs`. consider them binary | nothing to do
  2 |.conf  | text, auto | **please add**
  2 |.testlog  | only in `.git`. consider them binary | nothing to do
  2 |.png  | binary | you marked them, but omitting them should be sufficient as bin is default
  2 |.editorconfig  |  text, auto | done
  2 |.config  | text, auto | **please add**
  1 |.gitignore  | text, auto | **please add**
  1 |.xml  | currently only in `.git`. but can be treated as _text, auto_ | **please add**
  1 |.user  | VS file. should be in .gitignore. treat as binary | nothing to do
  1 |.partial  | DocFx templated file. _text, auto_ | **please add**

You also have other extensions (e.g. `*.sh`). We do not have them in the repo, but it's a good foresight. :)

2022-06-09 16:31 UTC, macrogreg commented on Src/SDK/Common/Temporal.Common.Payloads/public/PayloadContainers.Unnamed.SerializedDataBacked.cs
>                          catch (Exception ex)
I see a bunch of files with a diff that probably normalizes line endings. But I do not understand why it did not happen to all the files. I thought the normalization should affect pretty much every line across the repo. :)

Either way, should we have two PRs: one with just the actual changes and one with the big automatic re-normalization. I am not sure it this is actually necessary, up to you - just a thought. Reason for it might be to make merging to and from from old branches in forks easier.

2022-06-09 16:32 UTC, macrogreg commented on Src/.gitattributes
> +# Set the default behavior, in case people don't have core.autocrlf set.
Btw, I run the PS command on my local fork. It has files from https://github.com/temporalio/sdk-dotnet/pull/95 that are not yet merged. :)

2022-06-09 18:00 UTC, mightyshazam commented on Src/.gitattributes
> +# Set the default behavior, in case people don't have core.autocrlf set.
It's not in the root because I was looking at minimizing the blast radius of the change. Putting it in the Src folder guarantees that it only affects things in the Src folder.
I have no problem moving it to the root. We'll just have to be sure we have our list of types right.

2022-06-09 18:03 UTC, mightyshazam commented on Src/SDK/Common/Temporal.Common.Payloads/public/PayloadContainers.Unnamed.SerializedDataBacked.cs
>                          catch (Exception ex)
I expected it to update every file, but it appears it only updated files we've both touched. I'm beginning to suspect that the initial issue was just due to some settings that were misconfigured on my end. VS may have been normalizing your line endings for you while my original settings were not normalizing line endings.

2022-06-09 22:08 UTC, mightyshazam commented on Src/.gitattributes
> +# Set the default behavior, in case people don't have core.autocrlf set.
I relocated the file and added the missing types

2022-06-11 01:15 UTC, macrogreg approved these changes

2022-06-11 01:16 UTC, macrogreg commented on Src/SDK/Common/Temporal.Common.Payloads/public/PayloadContainers.Unnamed.SerializedDataBacked.cs
>                          catch (Exception ex)
Well, I think, we created goodness anyway.. :)
LGTM, please take note of this: https://github.com/temporalio/sdk-dotnet/pull/92#discussion_r894958160

2022-06-11 01:16 UTC, macrogreg commented on Src/.gitattributes
> +# Set the default behavior, in case people don't have core.autocrlf set.
👍

2022-06-11 01:47 UTC, mightyshazam commented on .gitattributes
> +.partial text=auto
I had *.partial. The push never went through. It's in now.

2022-06-11 02:41 UTC, merged